### ISSUE TITLE
Using all available options for the S3 constructor

### ISSUE THREAD

**Issue by xelmed** [jsreport/jsreport-fs-store-aws-s3-persistence#1]
Hello!

Could you consider an opportunity to add a way for using all available options in the S3 constructor?
Now, when an instance of S3 is created, it is always added with accessKeyId and secretAccessKey only.
`const s3 = new S3({ accessKeyId: accessKeyId, secretAccessKey: secretAccessKey })`

Maybe, it would be better to add a block "options"  to fs-store-aws-s3-persistence's properties and then use it as 
`module.exports = ({ logger, accessKeyId, secretAccessKey, bucket, lock = { }, options = {} }) => {
.......
const s3 = new S3(options)`
It would provide us with an opportunity to configure S3 better.
Like for instance, it is necessary when using different repositories providing S3 interface like as Minio.

Yours sincerely,
Yuriy Gerasimov

**Comment by pofider** [comment]
Thank you for suggestion.
Unfortunately I missed the notification and just found it.
I apologize for such delay, but there is now `s3Options` configuration to support it.

**Comment by pofider** [comment]
Released in 1.2.0
